#!/bin/bash

DIR=$1;
if ! [ "${DIR:0:1}" = "/" ]
then
        DIR=$(pwd)/$DIR
fi

sudo rm -rf $DIR/app/cache/*
sudo chmod 777 -Rf $DIR/app/cache/*
sudo chmod 777 -Rf $DIR/app/logs/*
sudo setfacl -R -m u:www-data:rwX -m u:`whoami`:rwX $DIR/app/cache $DIR/app/logs
sudo setfacl -dR -m u:www-data:rwx -m u:`whoami`:rwx $DIR/app/cache $DIR/app/logs

